### ISSUE TITLE
Nginx 413 File too Large error when download pchemprop batch CSV

### ISSUE THREAD

**Issue by popenc** [quanted/cts_app#12]
After pchemprop batch mode run of even just 3 molecules (getting all calcs and props), the CSV downloads up until 50+%, then a 413 error is returned.

Added "client_max_body_size 4M;" to server 1's nginx.conf, but the error was not resolved.

**Comment by popenc** [comment]
Getting the following DJANGO exception now, not a 413 through nginx...


```
qed_django_1       | Traceback (most recent call last):
qed_django_1       |   File "/usr/local/lib/python2.7/site-packages/django/core/handlers/wsgi.py",          line 170, in __call__
qed_django_1       |     response = self.get_response(request)
qed_django_1       |   File "/usr/local/lib/python2.7/site-packages/django/core/handlers/base.py",          line 124, in get_response
qed_django_1       |     response = self._middleware_chain(request)
qed_django_1       |   File "/usr/local/lib/python2.7/site-packages/django/core/handlers/exception         .py", line 41, in inner
qed_django_1       |     response = response_for_exception(request, exc)
qed_django_1       |   File "/usr/local/lib/python2.7/site-packages/django/core/handlers/exception         .py", line 73, in response_for_exception
qed_django_1       |     extra={'status_code': 400, 'request': request},
qed_django_1       |   File "/usr/local/lib/python2.7/logging/__init__.py", line 1193, in error
qed_django_1       |     self._log(ERROR, msg, args, **kwargs)
qed_django_1       |   File "/usr/local/lib/python2.7/logging/__init__.py", line 1286, in _log
qed_django_1       |     self.handle(record)
qed_django_1       |   File "/usr/local/lib/python2.7/logging/__init__.py", line 1296, in handle
qed_django_1       |     self.callHandlers(record)
qed_django_1       |   File "/usr/local/lib/python2.7/logging/__init__.py", line 1336, in callHand         lers
qed_django_1       |     hdlr.handle(record)
qed_django_1       |   File "/usr/local/lib/python2.7/logging/__init__.py", line 759, in handle
qed_django_1       |     self.emit(record)
qed_django_1       |   File "/usr/local/lib/python2.7/site-packages/django/utils/log.py", line 119         , in emit
qed_django_1       |     message = "%s\n\n%s" % (self.format(no_exc_record), reporter.get_tracebac         k_text())
qed_django_1       |   File "/usr/local/lib/python2.7/site-packages/django/views/debug.py", line 3         34, in get_traceback_text
qed_django_1       |     c = Context(self.get_traceback_data(), autoescape=False, use_l10n=False)
qed_django_1       |   File "/usr/local/lib/python2.7/site-packages/django/views/debug.py", line 3         04, in get_traceback_data
qed_django_1       |     'filtered_POST': self.filter.get_post_parameters(self.request),
qed_django_1       |   File "/usr/local/lib/python2.7/site-packages/django/views/debug.py", line 1         67, in get_post_parameters
qed_django_1       |     return request.POST
qed_django_1       |   File "/usr/local/lib/python2.7/site-packages/django/core/handlers/wsgi.py",          line 128, in _get_post
qed_django_1       |     self._load_post_and_files()
qed_django_1       |   File "/usr/local/lib/python2.7/site-packages/django/http/request.py", line          311, in _load_post_and_files
qed_django_1       |     self._post, self._files = QueryDict(self.body, encoding=self._encoding),          MultiValueDict()
qed_django_1       |   File "/usr/local/lib/python2.7/site-packages/django/http/request.py", line          269, in body
qed_django_1       |     raise RequestDataTooBig('Request body exceeded settings.DATA_UPLOAD_MAX_M         EMORY_SIZE.')
qed_django_1       | django.core.exceptions.RequestDataTooBig: Request body exceeded settings.DATA         _UPLOAD_MAX_MEMORY_SIZE.

```

**Comment by popenc** [comment]
django.core.exceptions.RequestDataTooBig -- "Request body exceeded settings.DATA_UPLOAD_MAX_MEMORY_SIZE."

^ Being triggered with at the following file/block:

`try:
        logging.warning("Request POST: {}".format(request.POST))
        request_data = request.POST.get('run_data')
        run_data = json.loads(request_data)
    except Exception as error:
        raise error`

Specifically, this part is causing the exception:

`request.POST`

**Comment by popenc** [comment]
Set DATA_UPLOAD_MAX_MEMORY_SIZE to 10MB (10485760 Bytes) in cts_app/views/ctsGenerateReport.py, csvReceiver() function.
