### ISSUE TITLE
Usage Analytics

### ISSUE THREAD

**Issue by popenc** [quanted/cts_app#150]
Get reports on site usage.

**Comment by popenc** [comment]
Things to track: 
- Filter by extension, .edu, .gov, etc.
- Where are the requests coming from? Industry? EPA? Private? Individual? 
- Which workflows get the most use? 
- Which reaction libraries or property calculators are being request? 
- Some of this info would be in the logs as well.

**Comment by popenc** [comment]
Currently, GA4 doesn't have an option to use scheduled weekly reports as emails. One possibility for automated reports would be to use the GA data API: https://developers.google.com/analytics/devguides/reporting/data/v1/quickstart-client-libraries.

Running the quickstart example in Python shows this error:
```
Traceback (most recent call last):
  File "/mnt/c/Users/inick/OneDrive/Documents/Projects/ga4_api/env/lib/python3.8/site-packages/google/api_core/grpc_helpers.py", line 72, in error_remapped_callable
    return callable_(*args, **kwargs)
  File "/mnt/c/Users/inick/OneDrive/Documents/Projects/ga4_api/env/lib/python3.8/site-packages/grpc/_channel.py", line 946, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/mnt/c/Users/inick/OneDrive/Documents/Projects/ga4_api/env/lib/python3.8/site-packages/grpc/_channel.py", line 849, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
        status = StatusCode.PERMISSION_DENIED
        details = "User does not have sufficient permissions for this property. To learn more about Property ID, see https://developers.google.com/analytics/devguides/reporting/data/v1/property-id."
        debug_error_string = "UNKNOWN:Error received from peer ipv4:64.233.185.95:443 {created_time:"2022-10-31T13:22:13.2383205-04:00", grpc_status:7, grpc_message:"User does not have sufficient permissions for this property. To learn more about Property ID, see https://developers.google.com/analytics/devguides/reporting/data/v1/property-id."}"
```
More specifically, "User does not have sufficient permissions for this property."

**Comment by popenc** [comment]
Link to specific workflows and pages viewed over this year: https://analytics.google.com/analytics/web/?authuser=0&hl=en_US&utm_source=pdfReportLink#/p293428315/reports/explorer?params=_u..nav%3Dmaui%26_u.dateOption%3DyearToDate%26_u.comparisonOption%3Ddisabled%26_r.explorerCard..startRow%3D0%26_r.explorerCard..rowsPerPage%3D50&r=4248465158&ruid=all-pages-and-screens,life-cycle,engagement&collectionId=4248502978

**Comment by popenc** [comment]
Going through tutorial again (https://developers.google.com/analytics/devguides/reporting/data/v1/quickstart-client-libraries). This time testing with test Gmail account, ctsemailserver@gmail.com.

**Comment by popenc** [comment]
Trying to run report generation scripts as a scheduled job with GitHub Actions. Currently working out how to properly handle sensitive information using secrets variables in GH Actions, but running into issues echoing a secret into a file. Seems like the echo of the variable gets masked, and that literal masked value gets populated into the file:

`google.auth.exceptions.DefaultCredentialsError: ('File *** is not a valid json file.', JSONDecodeError('Expecting value: line 2 column 1 (char 1)'))`

**Comment by popenc** [comment]
Basic report now being generated; code repo: https://github.com/quanted/ga_reports. Using GitHub Actions to run Python script every Friday at 5:00PM EST for weekly, monthly, and yearly data. Weekly and monthly are for 7 and 30 days ago from that Friday, and yearly is from January 1st of the current year up until that Friday.

Next steps are adding more detail in the reports and testing it for multiple google analytics properties (i.e., QED apps in general).

**Comment by popenc** [comment]
Updated reports to provide more plots and plot information. Also configured it to email to cts@epa.gov.

**Comment by popenc** [comment]
I would consider this a closed issue as it's now been generating reports every Friday for some time now. A new issue can be created for adding any additional data to the reports.
