### ISSUE TITLE
PDF download Errno 10053 mystery issue

### ISSUE THREAD

**Issue by popenc** [quanted/cts_app#18]
Downloading a PDF is sometimes taking two clicks to activate, and when it is activated, it builds the PDF, but chokes when trying to return the response. NOTE: This isn't happening with firefox, just chrome.

`2017-02-07 07:13:46,513 DEBUG Col widths: ['16.6666666667%', '16.6666666667%', '16.6666666667%', '16.6666666667%', '16.6666666667%', '16.6666666667%']
2017-02-07 07:13:46,640 DEBUG Col widths: []
2017-02-07 07:13:46,641 WARNING <table> is empty
u'<tr style="display:none"><td/></tr>'
[07/Feb/2017 07:13:47] "POST /cts/pchemprop/pdf HTTP/1.1" 200 59485
Traceback (most recent call last):
  File "C:\Python27\Lib\wsgiref\handlers.py", line 86, in run
    self.finish_response()
  File "C:\Python27\Lib\wsgiref\handlers.py", line 128, in finish_response
    self.write(data)
  File "C:\Python27\Lib\wsgiref\handlers.py", line 212, in write
    self.send_headers()
  File "C:\Python27\Lib\wsgiref\handlers.py", line 270, in send_headers
    self.send_preamble()
  File "C:\Python27\Lib\wsgiref\handlers.py", line 194, in send_preamble
    'Date: %s\r\n' % format_date_time(time.time())
  File "C:\Python27\Lib\socket.py", line 328, in write
    self.flush()
  File "C:\Python27\Lib\socket.py", line 307, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 10053] An established connection was aborted by the software in your host machine
[07/Feb/2017 07:13:47] "POST /cts/pchemprop/pdf HTTP/1.1" 500 59
Traceback (most recent call last):
  File "C:\Python27\Lib\SocketServer.py", line 596, in process_request_thread
    self.finish_request(request, client_address)
  File "C:\Python27\Lib\SocketServer.py", line 331, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "C:\Python27\Lib\SocketServer.py", line 654, in __init__
    self.finish()
  File "C:\Python27\Lib\SocketServer.py", line 713, in finish
    self.wfile.close()
  File "C:\Python27\Lib\socket.py", line 283, in close
    self.flush()
  File "C:\Python27\Lib\socket.py", line 307, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 10053] An established connection was aborted by the software in your host machine
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 8047)
----------------------------------------`

**Comment by popenc** [comment]
The mystery's making more sense... Two requests are coming into django backend, and this is the one that's unexpected:

`2017-02-07 07:34:58,990 INFO REQUEST POST: <QueryDict: {u'result_template': [u'2col.ftl'], u'areasearchurl': [u''], u'typeofsearch': [u'epa'], u'areacontacts': [u''], u'querytext': [u''], u'areaname': [u'']}>`

**Comment by popenc** [comment]
CTS needs to grab POST form by class name instead of just 'form.' It's picking up the following during form submit (from  02epa_drupal_header_bluestripe.html):

`<form class="epa-search" method="get" action="https://search.epa.gov/epasearch/epasearch">
      <label class="element-hidden" for="search-box">Search</label>
      <input class="form-text" placeholder="Search EPA.gov" name="querytext" id="search-box" value=""/>
      <button class="epa-search-button" id="search-button" type="submit" title="Search">Search</button>
      <input type="hidden" name="areaname" value="" />
      <input type="hidden" name="areacontacts" value="" />
      <input type="hidden" name="areasearchurl" value="" />
      <input type="hidden" name="typeofsearch" value="epa" />
      <input type="hidden" name="result_template" value="2col.ftl" />
    </form>`

**Comment by popenc** [comment]
This is now working for single mode PDFs and p-chem workflow's batch mode, but still no CSV downloads for speciation workflow. Closing this and adding as separate issue.
